import type { Metadata } from 'next'
import Sidebar from './components/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="h-screen md:hidden w-full bg-black  flex items-center justify-center">
        <h1 className="text-white text-xl">For access admin page, please using dekstop mode!</h1>
      </div>
      <main className="hidden md:block">
        <Sidebar />
        <section className="fixed right-0 bg-hard-color h-screen w-4/5 overflow-y-auto">{children}</section>
      </main>
    </>
  )
}
